# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.107.0"

default_platform :ios

platform :ios do
  scheme = "Gift Exchange"
  device = "iPhone SE"

  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    # cocoapods
  end

  desc "Prints out the current build info"
  lane :build_info do
    #build_number = increment_build_number(build_number: 2)
    build_number = get_build_number
    build_version = get_version_number
    UI.message("#{build_version} - #{build_number}")
  end

  desc "Runs all the tests"
  lane :test do
    scan(scheme: scheme, device: device)
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    ENV["PROFILE_UDID"] = lane_context[SharedValues::SIGH_UDID]
    build_number = increment_build_number
    build_version = get_version_number
    gym(scheme: "Gift Exchange", export_method: 'app-store') # Build your app - more options available
    pilot
    commit_version_bump(
      message: "[Build Bump] #{build_version}-#{build_number}",
      force: true
    )

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "Gift Exchange") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
